version: '3'
services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: production
      APP_KEY: your-app-key-here
      DB_CONNECTION: mysql
      DB_HOST: your-database-host
      DB_PORT: 3306
      DB_DATABASE: your-database-name
      DB_USERNAME: your-database-user
      DB_PASSWORD: your-database-password
